name: Build and Publish Base Docker Image

on:
  workflow_dispatch:

jobs:
  build-base-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: jpereiramp/outline

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push base Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.base
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/outline-base:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/outline-base:${{ github.sha }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
